import type { LevelConfig } from '../types/game.types';

// NOTE: runway positions are expressed in a 800×600 logical canvas space.
// The renderer scales them proportionally to actual canvas size.

const OEBA = { id: 'oeba', icao: 'OEBA', name: 'Al Baha Airport' };
const OETF = { id: 'oetf', icao: 'OETF', name: 'Taif Airport' };
const OEJN = { id: 'oejn', icao: 'OEJN', name: 'Jeddah King Abdulaziz' };

const LEVEL_1: LevelConfig = {
  id: 1,
  name: 'OEBA Al Baha',
  subtitle: 'OEBA — Runway 07/25',
  airport: OEBA,
  runways: [
    {
      id: 'oeba-rwy-07-25',
      airportId: OEBA.id,
      type: 'long',
      position: { x: 400, y: 650 },
      angle: 70,
      length: 180,
      width: 22,
      label: '07/25',
    },
    {
      id: 'oeba-h1',
      airportId: OEBA.id,
      type: 'helipad',
      position: { x: 160, y: 450 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'H1',
    },
  ],
  spawnRateMs: 6000,
  maxAircraft: 3,
  allowedTypes: ['cessna', 'jetliner', 'helicopter'],
  typeWeights: { cessna: 4, jetliner: 3, fighter: 0, helicopter: 2 },
  hasRadarSweep: false,
  hasWindShear: false,
  windDirection: 90,
  windStrength: 0,
  visibilityRadius: Infinity,
  backgroundStars: false,
};

const LEVEL_2: LevelConfig = {
  id: 2,
  name: 'OETF Taif',
  subtitle: 'OETF — Runways 25/07 and 35/17',
  airport: OETF,
  runways: [
    {
      id: 'oetf-rwy-25-07',
      airportId: OETF.id,
      type: 'long',
      position: { x: 400, y: 620 },
      angle: 250,
      length: 175,
      width: 20,
      label: '25/07',
    },
    {
      id: 'oetf-rwy-35-17',
      airportId: OETF.id,
      type: 'long',
      position: { x: 400, y: 620 },
      angle: 350,
      length: 175,
      width: 20,
      label: '35/17',
    },
    {
      id: 'oetf-h1',
      airportId: OETF.id,
      type: 'helipad',
      position: { x: 150, y: 430 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'H1',
    },
    {
      id: 'oetf-h2',
      airportId: OETF.id,
      type: 'helipad',
      position: { x: 650, y: 430 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'H2',
    },
  ],
  spawnRateMs: 4500,
  maxAircraft: 5,
  allowedTypes: ['cessna', 'jetliner', 'helicopter'],
  typeWeights: { cessna: 3, jetliner: 4, fighter: 0, helicopter: 2 },
  hasRadarSweep: false,
  hasWindShear: true,
  windDirection: 120,
  windStrength: 8,
  visibilityRadius: Infinity,
  backgroundStars: false,
};

const LEVEL_3: LevelConfig = {
  id: 3,
  name: 'OETF Tactical',
  subtitle: 'OETF — Military and Medevac Ops',
  airport: OETF,
  runways: [
    {
      id: 'oetf-tac-rwy-25-07',
      airportId: OETF.id,
      type: 'long',
      position: { x: 400, y: 610 },
      angle: 250,
      length: 185,
      width: 22,
      label: '25/07',
    },
    {
      id: 'oetf-tac-rwy-35-17',
      airportId: OETF.id,
      type: 'long',
      position: { x: 400, y: 610 },
      angle: 350,
      length: 175,
      width: 20,
      label: '35/17',
    },
    {
      id: 'oetf-tac-h1',
      airportId: OETF.id,
      type: 'helipad',
      position: { x: 140, y: 400 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'H1',
    },
    {
      id: 'oetf-tac-h2',
      airportId: OETF.id,
      type: 'helipad',
      position: { x: 660, y: 760 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'H2',
    },
  ],
  spawnRateMs: 3200,
  maxAircraft: 7,
  allowedTypes: ['cessna', 'jetliner', 'fighter', 'helicopter'],
  typeWeights: { cessna: 1, jetliner: 2, fighter: 5, helicopter: 3 },
  hasRadarSweep: false,
  hasWindShear: true,
  windDirection: 200,
  windStrength: 12,
  visibilityRadius: Infinity,
  backgroundStars: false,
};

const LEVEL_4: LevelConfig = {
  id: 4,
  name: 'OEBA IFR',
  subtitle: 'OEBA — Low Visibility 07/25',
  airport: OEBA,
  runways: [
    {
      id: 'oeba-ifr-rwy-07-25',
      airportId: OEBA.id,
      type: 'long',
      position: { x: 400, y: 610 },
      angle: 70,
      length: 185,
      width: 22,
      label: '07/25',
    },
    {
      id: 'oeba-ifr-h1',
      airportId: OEBA.id,
      type: 'helipad',
      position: { x: 155, y: 410 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'H1',
    },
    {
      id: 'oeba-ifr-h2',
      airportId: OEBA.id,
      type: 'helipad',
      position: { x: 645, y: 410 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'H2',
    },
  ],
  spawnRateMs: 2800,
  maxAircraft: 9,
  allowedTypes: ['cessna', 'jetliner', 'fighter', 'helicopter'],
  typeWeights: { cessna: 2, jetliner: 3, fighter: 4, helicopter: 2 },
  hasRadarSweep: true,
  hasWindShear: true,
  windDirection: 270,
  windStrength: 20,
  visibilityRadius: 120,
  backgroundStars: true,
};

const LEVEL_5: LevelConfig = {
  id: 5,
  name: 'OEBA Storm',
  subtitle: 'OEBA — Mountain Storm Approach',
  airport: OEBA,
  runways: [
    {
      id: 'oeba-storm-rwy-07-25',
      airportId: OEBA.id,
      type: 'short',
      position: { x: 400, y: 700 },
      angle: 70,
      length: 130,
      width: 18,
      label: '07/25',
    },
    {
      id: 'oeba-storm-h1',
      airportId: OEBA.id,
      type: 'helipad',
      position: { x: 400, y: 300 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'H1',
    },
  ],
  spawnRateMs: 3500,
  maxAircraft: 5,
  allowedTypes: ['cessna', 'helicopter'],
  typeWeights: { cessna: 4, jetliner: 0, fighter: 0, helicopter: 4 },
  hasRadarSweep: false,
  hasWindShear: true,
  windDirection: 315,
  windStrength: 25,
  visibilityRadius: Infinity,
  backgroundStars: false,
};

const LEVEL_6: LevelConfig = {
  id: 6,
  name: 'OEJN Jeddah',
  subtitle: 'OEJN — Triple Parallel Runways',
  airport: OEJN,
  runways: [
    {
      id: 'oejn-rwy-34c-16c',
      airportId: OEJN.id,
      type: 'long',
      position: { x: 200, y: 600 },
      angle: 340,
      length: 175,
      width: 20,
      label: '34C/16C',
    },
    {
      id: 'oejn-rwy-34l-16r',
      airportId: OEJN.id,
      type: 'long',
      position: { x: 400, y: 600 },
      angle: 340,
      length: 175,
      width: 20,
      label: '34L/16R',
    },
    {
      id: 'oejn-rwy-34r-16l',
      airportId: OEJN.id,
      type: 'long',
      position: { x: 600, y: 600 },
      angle: 340,
      length: 175,
      width: 20,
      label: '34R/16L',
    },
  ],
  spawnRateMs: 2000,
  maxAircraft: 11,
  allowedTypes: ['jetliner'],
  typeWeights: { cessna: 0, jetliner: 1, fighter: 0, helicopter: 0 },
  hasRadarSweep: false,
  hasWindShear: false,
  windDirection: 90,
  windStrength: 0,
  visibilityRadius: Infinity,
  backgroundStars: false,
};

const LEVEL_7: LevelConfig = {
  id: 7,
  name: 'OETF Emergency',
  subtitle: 'OETF — Emergency and Medevac',
  airport: OETF,
  runways: [
    {
      id: 'oetf-emg-rwy-25-07',
      airportId: OETF.id,
      type: 'long',
      position: { x: 400, y: 400 },
      angle: 250,
      length: 190,
      width: 22,
      label: '25/07',
    },
    {
      id: 'oetf-emg-rwy-35-17',
      airportId: OETF.id,
      type: 'long',
      position: { x: 400, y: 560 },
      angle: 350,
      length: 175,
      width: 20,
      label: '35/17',
    },
    {
      id: 'oetf-emg-h1',
      airportId: OETF.id,
      type: 'helipad',
      position: { x: 200, y: 400 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'H1',
    },
    {
      id: 'oetf-emg-h2',
      airportId: OETF.id,
      type: 'helipad',
      position: { x: 600, y: 400 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'H2',
    },
  ],
  spawnRateMs: 2500,
  maxAircraft: 7,
  allowedTypes: ['fighter', 'helicopter'],
  typeWeights: { cessna: 0, jetliner: 0, fighter: 6, helicopter: 4 },
  hasRadarSweep: false,
  hasWindShear: true,
  windDirection: 45,
  windStrength: 10,
  visibilityRadius: Infinity,
  backgroundStars: false,
};

const LEVEL_8: LevelConfig = {
  id: 8,
  name: 'OEJN Midnight',
  subtitle: 'OEJN — Full Night Operations',
  airport: OEJN,
  runways: [
    {
      id: 'oejn-night-rwy-34c-16c',
      airportId: OEJN.id,
      type: 'long',
      position: { x: 220, y: 500 },
      angle: 340,
      length: 175,
      width: 20,
      label: '34C/16C',
    },
    {
      id: 'oejn-night-rwy-34l-16r',
      airportId: OEJN.id,
      type: 'long',
      position: { x: 400, y: 500 },
      angle: 340,
      length: 175,
      width: 20,
      label: '34L/16R',
    },
    {
      id: 'oejn-night-rwy-34r-16l',
      airportId: OEJN.id,
      type: 'long',
      position: { x: 580, y: 500 },
      angle: 340,
      length: 175,
      width: 20,
      label: '34R/16L',
    },
    {
      id: 'oejn-night-h1',
      airportId: OEJN.id,
      type: 'helipad',
      position: { x: 400, y: 200 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'H1',
    },
  ],
  spawnRateMs: 1800,
  maxAircraft: 13,
  allowedTypes: ['cessna', 'jetliner', 'fighter', 'helicopter'],
  typeWeights: { cessna: 2, jetliner: 3, fighter: 2, helicopter: 2 },
  hasRadarSweep: true,
  hasWindShear: true,
  windDirection: 180,
  windStrength: 15,
  visibilityRadius: 90,
  backgroundStars: true,
};

export const LEVELS: LevelConfig[] = [LEVEL_1, LEVEL_2, LEVEL_3, LEVEL_4, LEVEL_5, LEVEL_6, LEVEL_7, LEVEL_8];
