import type { LevelConfig } from '../types/game.types';

// NOTE: runway positions are expressed in a 800×600 logical canvas space.
// The renderer scales them proportionally to actual canvas size.

const LEVEL_1: LevelConfig = {
  id: 1,
  name: 'OETF Approach',
  subtitle: 'Single Runway — Clear Weather',
  runways: [
    {
      id: 'rwy-09L',
      type: 'long',
      position: { x: 400, y: 650 },
      angle: 90,          // East-West runway
      length: 130,
      width: 16,
      label: '09L/27R',
    },
    {
      id: 'hpad-01',
      type: 'helipad',
      position: { x: 160, y: 450 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'H1',
    },
  ],
  spawnRateMs: 6000,
  maxAircraft: 4,
  allowedTypes: ['cessna', 'jetliner', 'helicopter'],
  typeWeights: { cessna: 4, jetliner: 3, fighter: 0, helicopter: 2 },
  hasRadarSweep: false,
  hasWindShear: false,
  windDirection: 90,
  windStrength: 0,
  visibilityRadius: Infinity,
  backgroundStars: false,
};

const LEVEL_2: LevelConfig = {
  id: 2,
  name: 'Crosswinds',
  subtitle: 'Intersecting Runways — Faster Traffic',
  runways: [
    {
      id: 'rwy-09L',
      type: 'long',
      position: { x: 400, y: 620 },
      angle: 90,
      length: 130,
      width: 16,
      label: '09L/27R',
    },
    {
      id: 'rwy-18R',
      type: 'long',
      position: { x: 400, y: 620 },
      angle: 0,
      length: 130,
      width: 16,
      label: '18R/36L',
    },
    {
      id: 'rwy-short',
      type: 'short',
      position: { x: 620, y: 760 },
      angle: 135,
      length: 80,
      width: 12,
      label: '13/31',
    },
    {
      id: 'hpad-01',
      type: 'helipad',
      position: { x: 150, y: 430 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'H1',
    },
    {
      id: 'hpad-02',
      type: 'helipad',
      position: { x: 650, y: 430 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'H2',
    },
  ],
  spawnRateMs: 4500,
  maxAircraft: 6,
  allowedTypes: ['cessna', 'jetliner', 'helicopter'],
  typeWeights: { cessna: 3, jetliner: 4, fighter: 0, helicopter: 2 },
  hasRadarSweep: false,
  hasWindShear: true,
  windDirection: 120,
  windStrength: 8,
  visibilityRadius: Infinity,
  backgroundStars: false,
};

const LEVEL_3: LevelConfig = {
  id: 3,
  name: 'Tactical Airbase',
  subtitle: 'Military Jets + Medevac Helicopters',
  runways: [
    {
      id: 'rwy-main',
      type: 'long',
      position: { x: 400, y: 610 },
      angle: 80,
      length: 140,
      width: 16,
      label: '08/26',
    },
    {
      id: 'rwy-aux',
      type: 'long',
      position: { x: 400, y: 610 },
      angle: 170,
      length: 130,
      width: 14,
      label: '17/35',
    },
    {
      id: 'rwy-short',
      type: 'short',
      position: { x: 190, y: 740 },
      angle: 45,
      length: 80,
      width: 12,
      label: '04/22',
    },
    {
      id: 'hpad-med',
      type: 'helipad',
      position: { x: 140, y: 400 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'MEDEVAC',
    },
    {
      id: 'hpad-ops',
      type: 'helipad',
      position: { x: 660, y: 760 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'OPS',
    },
  ],
  spawnRateMs: 3200,
  maxAircraft: 8,
  allowedTypes: ['cessna', 'jetliner', 'fighter', 'helicopter'],
  typeWeights: { cessna: 1, jetliner: 2, fighter: 5, helicopter: 3 },
  hasRadarSweep: false,
  hasWindShear: true,
  windDirection: 200,
  windStrength: 12,
  visibilityRadius: Infinity,
  backgroundStars: false,
};

const LEVEL_4: LevelConfig = {
  id: 4,
  name: 'IFR Conditions',
  subtitle: 'Low Visibility — Radar Sweep Only',
  runways: [
    {
      id: 'rwy-ifr-main',
      type: 'long',
      position: { x: 400, y: 610 },
      angle: 90,
      length: 140,
      width: 16,
      label: '09/27',
    },
    {
      id: 'rwy-ifr-cross',
      type: 'long',
      position: { x: 400, y: 610 },
      angle: 0,
      length: 130,
      width: 14,
      label: '18/36',
    },
    {
      id: 'rwy-ifr-short',
      type: 'short',
      position: { x: 600, y: 750 },
      angle: 60,
      length: 80,
      width: 12,
      label: '06/24',
    },
    {
      id: 'hpad-ifr-1',
      type: 'helipad',
      position: { x: 155, y: 410 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'H-IFR',
    },
    {
      id: 'hpad-ifr-2',
      type: 'helipad',
      position: { x: 645, y: 410 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'H-OPS',
    },
  ],
  spawnRateMs: 2800,
  maxAircraft: 10,
  allowedTypes: ['cessna', 'jetliner', 'fighter', 'helicopter'],
  typeWeights: { cessna: 2, jetliner: 3, fighter: 4, helicopter: 2 },
  hasRadarSweep: true,
  hasWindShear: true,
  windDirection: 270,
  windStrength: 20,
  visibilityRadius: 120,
  backgroundStars: true,
};

const LEVEL_5: LevelConfig = {
  id: 5,
  name: 'Storm Front',
  subtitle: 'High Winds — Light Aircraft',
  runways: [
    {
      id: 'rwy-storm',
      type: 'short',
      position: { x: 400, y: 700 },
      angle: 45,
      length: 100,
      width: 14,
      label: '04/22',
    },
    {
      id: 'hpad-storm',
      type: 'helipad',
      position: { x: 400, y: 300 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'STORM',
    },
  ],
  spawnRateMs: 3500,
  maxAircraft: 6,
  allowedTypes: ['cessna', 'helicopter'],
  typeWeights: { cessna: 4, jetliner: 0, fighter: 0, helicopter: 4 },
  hasRadarSweep: false,
  hasWindShear: true,
  windDirection: 315,
  windStrength: 25,
  visibilityRadius: Infinity,
  backgroundStars: false,
};

const LEVEL_6: LevelConfig = {
  id: 6,
  name: 'Heavy Traffic',
  subtitle: 'Commercial Hub — Jetliners Only',
  runways: [
    {
      id: 'rwy-parallel-1',
      type: 'long',
      position: { x: 250, y: 600 },
      angle: 90,
      length: 140,
      width: 16,
      label: '09L',
    },
    {
      id: 'rwy-parallel-2',
      type: 'long',
      position: { x: 400, y: 600 },
      angle: 90,
      length: 140,
      width: 16,
      label: '09C',
    },
    {
      id: 'rwy-parallel-3',
      type: 'long',
      position: { x: 550, y: 600 },
      angle: 90,
      length: 140,
      width: 16,
      label: '09R',
    },
  ],
  spawnRateMs: 2000,
  maxAircraft: 12,
  allowedTypes: ['jetliner'],
  typeWeights: { cessna: 0, jetliner: 1, fighter: 0, helicopter: 0 },
  hasRadarSweep: false,
  hasWindShear: false,
  windDirection: 90,
  windStrength: 0,
  visibilityRadius: Infinity,
  backgroundStars: false,
};

const LEVEL_7: LevelConfig = {
  id: 7,
  name: 'Emergency Protocol',
  subtitle: 'Military & Medevac — High Speed',
  runways: [
    {
      id: 'rwy-mil-1',
      type: 'long',
      position: { x: 400, y: 400 },
      angle: 0,
      length: 150,
      width: 18,
      label: '18/36',
    },
    {
      id: 'hpad-med-1',
      type: 'helipad',
      position: { x: 200, y: 400 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'MED-1',
    },
    {
      id: 'hpad-med-2',
      type: 'helipad',
      position: { x: 600, y: 400 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'MED-2',
    },
  ],
  spawnRateMs: 2500,
  maxAircraft: 8,
  allowedTypes: ['fighter', 'helicopter'],
  typeWeights: { cessna: 0, jetliner: 0, fighter: 6, helicopter: 4 },
  hasRadarSweep: false,
  hasWindShear: true,
  windDirection: 45,
  windStrength: 10,
  visibilityRadius: Infinity,
  backgroundStars: false,
};

const LEVEL_8: LevelConfig = {
  id: 8,
  name: 'Midnight Operations',
  subtitle: 'Complete Chaos — All Aircraft',
  runways: [
    {
      id: 'rwy-chaos-1',
      type: 'long',
      position: { x: 300, y: 500 },
      angle: 45,
      length: 130,
      width: 16,
      label: '04/22',
    },
    {
      id: 'rwy-chaos-2',
      type: 'short',
      position: { x: 500, y: 500 },
      angle: 135,
      length: 100,
      width: 14,
      label: '13/31',
    },
    {
      id: 'hpad-chaos-1',
      type: 'helipad',
      position: { x: 400, y: 200 },
      angle: 0,
      length: 36,
      width: 36,
      label: 'NIGHT',
    },
  ],
  spawnRateMs: 1800,
  maxAircraft: 14,
  allowedTypes: ['cessna', 'jetliner', 'fighter', 'helicopter'],
  typeWeights: { cessna: 2, jetliner: 3, fighter: 2, helicopter: 2 },
  hasRadarSweep: true,
  hasWindShear: true,
  windDirection: 180,
  windStrength: 15,
  visibilityRadius: 90,
  backgroundStars: true,
};

export const LEVELS: LevelConfig[] = [LEVEL_1, LEVEL_2, LEVEL_3, LEVEL_4, LEVEL_5, LEVEL_6, LEVEL_7, LEVEL_8];
